### PR TITLE
initial fastlane structures

### PR DESCRIPTION
**Pull request by IzzySoft**
With this you no longer need MRs at fdroiddata to update your description – and you can also include screenshots & more, see my [Fastlane Cheat Sheet](https://gitlab.com/snippets/1895688) for a quick guide.

### CODE REVIEW

**Comment by koiuo** [comment]
Thanks a lot @IzzySoft! This is very helpful.

Some quick context for @avuton: f-droid store allows so-called fast-lane submission. The idea is that we implement a certain conventional structure in our code repo, and then f-droid server (if I udnerstand correctly) can detect the changes and rebuild and publish new versions of our app without human intevention.

This looks ok to me (except for the old icon, which we can replace later). @avuton, please let us know if you are ok with this PR. In the meantime I'll work on a PR to f-droid repo to enable fastlane on their side.

**Comment by avuton** [comment]
Sounds great, I'll have time to take a look at it in a few hours. Thanks for the commit!

**Comment by IzzySoft** [comment]
Thanks @edio! Let me add some words to your explanation:

Fastlane is just for metadata (summary, description, icon, featureGraphic, screenshots, per-release changelogs – to name the most prominent; more details in above mentioned Cheat Sheet). Whenever F-Droid builds a new release (as you've tagged one), Fastlane gets pulled along (as it's part of the code base) and is used for the elements it provides. As that way summary & description are no longer part of the F-Droid "internal metadata", you – the ones who know best – are in full control of these parts *without needing to open merge requests* with F-Droid to get changes in.

> detect the changes and rebuild and publish new versions

That's done by your tagging and keeping tag name in sync with versionName. The updater checks for new tags, cross-checks them with their corresponding `build.gradle` – and if `versionName` matches plus `versionCode` is higher than the last version F-Droid has, it considers that an update and triggers the corresponding build process.

> the old icon, which we can replace later

Aha! OK, disclosure: that icon was just copied from `play_store/launcher_icon.png` – so make sure to replace both (or simply remove the latter while updating the one in fastlane, which might make the `play_store`  directory obsolete).

> I'll work on a PR to f-droid repo to enable fastlane on their side.

Great! Please wait with submitting that until this PR here is merged and a new version is tagged. As described, fastlane is taken from the very same tag the app is built from – so removing the description *before* having fastlane tagged will lead to "no description shown".

**Comment by IzzySoft** [comment]
Thanks for the merge! Can you please give me a ping once you've made the next tag/release covering this? I'd then take care to adjust on F-Droid's end (we must remove summary/description from the YAML file there, which otherwise "overwrites" what comes from fastlane). Disclosure: I'm one of the F-Droid maintainers, so I can do this quickly (hopefully) :wink:

**Pull request merged**
